[gcp_service_account]
type = "service_account"
project_id = "should-work-366905"
private_key_id = "46ad376336b1e840f5dd06372efe4760ccfc772d"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCj7wVl+WSgK2q9
YfNcJ3a2/S5cb2Fk1ZWhck8C4IrE7g41CRAnw89r3ImXFxZtF+hpDtIQVgtTJIRW
Uo65SDm7m/vTy5FBupcJGs8i1xlwyyZCMgI/EKIdbJaGIYgac9HS5XPJD0BDz8wm
YYBCPa2tQdnVh6ViPIj/g45tT+58fiXQSqUioMzynz8HvU5XkVcuF6NIdesmCgvX
QXf3Xcgv7P3FqdWVX1S59jilSAG3bn1TyK7ZzSSreqpC2NvHOtm8ktlQteGBht/F
nIlsh1P838vHXnp8AAOIkUcLGZnETxImjutiBnJoL4ZOMmZ+IOYLWwwyOeyVTtxC
rFU/k09FAgMBAAECggEAErAZznEqvnOUnHhBFN1O1DdyhIkR8jvC7f+o8CwGxcJZ
jkQ1OkNBLwuaB8ZTASa7kNZmrgQREG5WQ7zvlkGciz2R7KgFLBgIRbpvqIoa1Vfj
SaKHzQapZG9PjYTfDhzr633KwD3j1pcmr61nwKVlWh3qpkPrX5KFD5PAtcdp6XkM
7QMr0BCvQsqfGy76nDiSo4mz5D33rlir+mAppOW6wwwKN8Jt/RbOrYGcOlBfDM5C
HF/Ykahz3c94wPcSGRrChZqydONd6DtEU1OxzS5pvrRFZ5KUmJovVV0R9i9vA+MA
xtB3NKgKvcli0G0Hh/lvRrDVMsq6vuRFfIIInzzTwQKBgQDnBRBu4SC7tnAhBaEY
7pqZGNcwIgrJD5lolfThDISS7pEuqbLMAs+J632WIi81NOcMQPPn9NkJFLGVuQhn
o8zNiWbmjNcy3ZDJSSAKdwnLfhQ2haTfVfjEbS6AhQ0qMkxkjEeNL75T+FE6Z0yF
Zw7RiGWA+e9G3xuNWrvsP+FetQKBgQC1qOyJjEkYAN+6D769D8N8UraD36oVBYjr
y1EuMu5T0/0oYOt/mbrw3XhEWim2tfOWZtF0gIUIxJ8emPc9jAOYtimU9aFAJZ4B
bTzB0NpT2+Ubezk9j/OUg0zeVGJDzUorDlz0aeL8n1s+Tgsgr/dGkdOoogEPZogj
MLx1bZH4UQKBgG7sDI7gg2H93+rLFCWvcwVtWu0ee0U8uzDvR2vDIeiWqZjZHCM+
ej3Dl0I92aLXatSEX1gRRSBKElZMSI/SoyRRA9pQ54bhwYIUHVFJBKfzOmtPUfF2
CwLtVXWZ7M9E5U8l17kfomgZA49iR+iJqiDLN8lsuAm0WDtPxIlTxrc9AoGAAbDa
0sTtgT2w12iCG/xjk2qprDyOtrdgeOFhlg5/TWRxvMh6KKvjo45MKka0kLDM3Z+D
X5Q6qMQ7vuspkfcVqXw4ktxebdxrxhOgNyWcgp9PWJwjAkGuwLkgJAmhCISGpjPy
BYxewn8xODk9vUYmBRAiajVn0R7hMYKonmcwrqECgYBS1Y6AdG4vjcC5A4XhQXju
x3apY8EwwoI+3Fp2hyHj15ojtNx8mI3c7V9ga0GI+GPHN+9Y84s2PHB6XTMDDBLR
GCqea05cbb1ECJ/fs9uVpAEIjEs5MZdmJD0gbCaKra3dAQVqVjW7petid0rd/vxJ
3T5VaJn6HI5CV7jo97OhCA==
-----END PRIVATE KEY-----
"""
client_email = "please-work@should-work-366905.iam.gserviceaccount.com"
client_id = "104333205089173547358"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/please-work%40should-work-366905.iam.gserviceaccount.com"
