type = "service_account"
project_id = "capstone-project-365416"
private_key_id = "fa43b634419d56edc2a53d1aedcfd08831e74413"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMNryoJh9h4qrD
PLhBvjfOFPEDpN2owrdkiJLhZitPzoQ7oErsVZB9n70SS9Burn4TnopAK/LQItT8
evu1kV92i/PAVHvSlHL0yibrbbc+RBz6zXvnlUO5Sqhx1NTLBnGXJj6i0oZIjJjL
sLrJQwNP8HF07dTPeVp0laEW7vM0RcfPR2CNUhIxKhr7ZQz+u9QfxoX52f+vbKse
NFfIg6iUqrJ/Ht5lU9IXJ8C6DvuMIrgJyCt6NqRD5SFS8PAvygKgsSV3MlBbD+Kk
89DQRqCBokN28DiRnI1sOQiiuEg9vpLZ9ckxjCCeU0yUJLLBo5HR2dgyLfm2Gk1b
6EuBzxFBAgMBAAECggEACS5q0/qGza1VtRptRFNrieHqJhpK9vPuL+BuDiE8UEW+
LzoZND/yk5tTclejQt6of3RQzerL62yte76Bw5uKGbfYGS0TNhgDhRrzngEcTHne
fa4wZGyTE2kWYqvJd2lOQRfwl/x0Gh3sHrhO5Y6UPwtV5oZs23kexoAVsoTCvXZT
Fq2ikk7dh9qXhIA2HgegASFqOV0P5lXrNwPPaVnP/5jYVf6sIdfxSzWeZ37LqptD
4EdLWn8pq0v2sKcSsYYfTaHJvCdFCQpOkD3+cd+8Leos4o7n4ot3aOuXC4XwLUlJ
90CDd73r4Lrb3sH/WtqCfxhl5ZVxV5zIXnbijSNyuQKBgQD0lIAofxurrE85aDAU
ZIA7tJybFvUY0mrzLENb9TafB9vNBuzIpv8soysC3TBOb4wAt1xsWURNVMQXDtUU
fnYNVwM8xIFhsXUZRmgpnvzlBSz6oJl4u/tMXwoPwcHOoKGWeXts1tMVjHBmhT1B
s8pUeALLukFtKe0QuTHLwBhkNQKBgQDVv7uZMgOATdj7HEm5zwlUq9rd6qUxooHH
gLsfbu6Qv1gXDM7PdDaSrFacqeVPBrNCM0I0hoLayDzM35AIpWXIvQIcIz9REuB1
IdpaRPOKQQsAOffVu7VT9VWNF0QWX8boFhCP2ol26/ECJ5cb1ccM/dci4sKib+3Q
ZtQf7ElCXQKBgA6nw1Ip46eSyKCA/LiMGR76wJOOeZtGKIBvu42MEPzQhLwxWQjg
8NNk55PhWx6oEnSMiC453xzfImzbR6tVtI8yEpCWmcYX0xNzo5Qy4aZ7e+l8rBWO
9gzqePjevFU8TNJubxXjfXyCEM4j17rTIiGTm19HxtnatEjXQAOcfBmtAoGBAInJ
4l38DqO8Cz682o3r98DcU+ewZjMb5fs8cePud91Za6jYOc0jxjZA4Eh3gPmzgQUQ
1AHWIC523DLZfxkDvhxsMxr+YceampUHcKG2RyR9j2Di/W+LZHWt9itQrzSZIzjj
WGPTZcACksdnzBJGed1XGUNE2GEsNCqezumRQRyFAoGAe4YXsj5HiZCfOHB/nQCp
8hS+SmzxUI5n4ydfK9KstsbzQd4mXUhaS9u+3jS0hV2nUTEWHsZZ7dRk0v1lrHrY
i+Oy71qyZbIJ/q5EUWOEXeB6/JmbmEkdeXlykEPRaYvHTUQ/+/MgJTDRDHrAmxoy
kc4cYcJ0LIHqsMS8hR2fHF0=
-----END PRIVATE KEY-----
"""
client_email = "yarab-985@capstone-project-365416.iam.gserviceaccount.com"
client_id = "116208674938268348235"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/yarab-985%40capstone-project-365416.iam.gserviceaccount.com"
